const types = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_SIDEBAR_SHOW: 'TOGGLE_SIDEBAR_SHOW',
  TOGGLE_DEVICE: "TOGGLE_DEVICE",
  LOAD_MENU: 'LOAD_MENU',
  LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU'
}

export default types
